// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/analysis/{ticker}": {
            "post": {
                "description": "Performs a stock analysis based on the provided requestData",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "StockAnalysis"
                ],
                "summary": "Stock Analysis",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ticker stock symbol",
                        "name": "ticker",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Payload.StockAnalysisResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Errors.ErrorBadRequest"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Errors.ErrorInternal"
                        }
                    }
                }
            }
        },
        "/best-investments": {
            "get": {
                "description": "This endpoint calls the service responsible for identifying the best stocks for investment and returns the results in JSON.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stocks"
                ],
                "responses": {
                    "200": {
                        "description": "Successful operation",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Payload.StockResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Errors.ErrorInternal"
                        }
                    }
                }
            }
        },
        "/fetchstocks": {
            "post": {
                "responses": {}
            }
        },
        "/stockmarkets": {
            "get": {
                "description": "Returns a paginated list of stock markets.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "StockMarket"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "items",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "2024-03-05T15:04:05Z",
                        "description": "Date in format RFC3339",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "2025-03-05T15:04:05Z",
                        "description": "Date in format RFC3339",
                        "name": "endDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "Apple",
                        "description": "Name of company",
                        "name": "company",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of stock markets",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Payload.StockResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/Errors.ErrorBadRequest"
                        }
                    },
                    "404": {
                        "description": "Stock markets not found",
                        "schema": {
                            "$ref": "#/definitions/Errors.ErrorNotFound"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/Errors.ErrorInternal"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Errors.ErrorBadRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Error code.\nexample: 400",
                    "type": "integer",
                    "example": 400
                },
                "error": {
                    "description": "Error description.\nexample: \"Bad request\"",
                    "type": "string",
                    "example": "Bad request"
                },
                "message": {
                    "description": "Error message.\nexample: \"Invalid request, please verify your parameters.\"",
                    "type": "string",
                    "example": "Invalid request, please verify your parameters."
                }
            }
        },
        "Errors.ErrorInternal": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Error code.\nexample: 500",
                    "type": "integer",
                    "example": 500
                },
                "error": {
                    "description": "Error description.\nexample: \"Internal server error\"",
                    "type": "string",
                    "example": "Internal server error"
                },
                "message": {
                    "description": "Error message.\nexample: \"Internal server error, please try again later.\"",
                    "type": "string",
                    "example": "Internal server error, please try again later."
                }
            }
        },
        "Errors.ErrorNotFound": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Error code.\nexample: 404",
                    "type": "integer",
                    "example": 404
                },
                "error": {
                    "description": "Error description.\nexample: \"Not found\"",
                    "type": "string",
                    "example": "Not found"
                },
                "message": {
                    "description": "Error message.\nexample: \"Resource not found.\"",
                    "type": "string",
                    "example": "Resource not found."
                }
            }
        },
        "Payload.StockAnalysisResponse": {
            "type": "object",
            "properties": {
                "comment": {
                    "description": "Exemplo: \"Exemplo: O ativo possui potencial de valorização apesar do risco\"",
                    "type": "string",
                    "example": "Exemplo: O ativo possui potencial de valorização apesar do risco"
                },
                "debt_to_equity": {
                    "description": "Exemplo: 1.20",
                    "type": "number",
                    "example": 1.2
                },
                "dividend_yield": {
                    "description": "Exemplo: 2.15",
                    "type": "number",
                    "example": 2.15
                },
                "market_cap": {
                    "description": "Exemplo: 250000000000.00",
                    "type": "number",
                    "example": 250000000000
                },
                "pb_ratio": {
                    "description": "Exemplo: 3.45",
                    "type": "number",
                    "example": 3.45
                },
                "pe_ratio": {
                    "description": "Exemplo: 15.23",
                    "type": "number",
                    "example": 15.23
                },
                "price": {
                    "description": "Exemplo: 150.75",
                    "type": "number",
                    "example": 150.75
                },
                "reason": {
                    "description": "Exemplo: \"Exemplo: Alta taxa de PE em comparação à média do setor\"",
                    "type": "string",
                    "example": "Exemplo: Alta taxa de PE em comparação à média do setor"
                },
                "recommendation": {
                    "description": "Exemplo: \"Exemplo: Comprar este ativo\"",
                    "type": "string",
                    "example": "Exemplo: Comprar este ativo"
                },
                "score": {
                    "description": "Exemplo: 85",
                    "type": "integer",
                    "example": 85
                },
                "shouldInvest": {
                    "description": "Exemplo: true",
                    "type": "boolean",
                    "example": true
                },
                "ticker": {
                    "description": "Exemplo: \"AAPL\"",
                    "type": "string",
                    "example": "AAPL"
                }
            }
        },
        "Payload.StockResponse": {
            "type": "object",
            "required": [
                "ticker"
            ],
            "properties": {
                "action": {
                    "type": "string",
                    "example": "BUY"
                },
                "brokerage": {
                    "type": "string",
                    "example": "NASDAQ"
                },
                "company": {
                    "type": "string",
                    "example": "Apple Inc."
                },
                "rating_from": {
                    "type": "string",
                    "example": "4.5"
                },
                "rating_to": {
                    "type": "string",
                    "example": "5.0"
                },
                "target_from": {
                    "type": "string",
                    "example": "$69.00"
                },
                "target_to": {
                    "type": "string",
                    "example": "$74.00"
                },
                "ticker": {
                    "type": "string",
                    "example": "AAPL"
                },
                "time": {
                    "type": "string",
                    "example": "2020-01-01T00:00:00Z"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Stock Market API",
	Description:      "Stock market API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
